name: cnos_sam2
channels:
  - xformers
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.11
  - pip:
    - numpy==1.26.4
    - torch
    - torchvision
    - omegaconf
    - torchmetrics==0.10.3
    - fvcore
    - iopath
    - xformers
    - opencv-python 
    - pycocotools 
    - matplotlib 
    - onnxruntime 
    - onnx
    - scipy
    - ffmpeg
    - hydra-colorlog
    - hydra-core
    - gdown
    - pytorch-lightning==1.8.6
    - pandas
    - ruamel.yaml
    - pyrender
    - wandb
    - distinctipy
#    - git+https://github.com/facebookresearch/hand_tracking_toolkit.git
# bop https://github.com/thodan/bop_toolkit.git